# Generated by Django 4.2.18 on 2026-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Informe o id do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o rg do instrutor', max_length=10)),
                ('nome', models.CharField(help_text='Informe o nome do instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Informe a data de nascimento do instrutor')),
                ('telefone', models.CharField(help_text='Informe o número do instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o ddd', max_length=3, null=True)),
                ('codigoTitulo', models.CharField(help_text='Informe o número do instrutor', max_length=9)),
            ],
        ),
    ]
