# Generated by Django 4.2.18 on 2026-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_alter_instrutor_codigotitulo'),
        ('instrutor', '0007_alter_instrutor_rg'),
    ]

    operations = [
    ]
