# Generated by Django 4.2.18 on 2026-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0008_merge_20260617_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrutor',
            name='codigoTitulo',
        ),
    ]
