# Generated by Django 4.2.18 on 2026-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matrícula do aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do aluno', max_length=70)),
                ('data_inicial', models.DateField(help_text='Informe que horário o aluno começou a estudar')),
                ('data_final', models.DateField(help_text='Informe que horário o aluno terminou de estudar')),
            ],
        ),
    ]
