# Generated by Django 4.2.18 on 2026-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='datafinal',
            field=models.DateField(blank=True, help_text='Informe a data final do aluno', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='datainicial',
            field=models.DateField(help_text='Informe a data inicial do aluno', max_length=70),
        ),
    ]
