# Generated by Django 4.2.18 on 2026-06-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_final',
            field=models.DateField(help_text='Informe que horário o aluno terminou de estudar', null=True),
        ),
    ]
