# Generated by Django 4.2.18 on 2026-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_data_final'),
        ('aluno', '0004_alter_aluno_datafinal_alter_aluno_datainicial'),
    ]

    operations = [
    ]
