# Generated by Django 4.2.18 on 2026-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_merge_20260617_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_final',
        ),
    ]
