# Generated by Django 4.2.18 on 2026-06-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Número da turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Informe o horário da aula')),
                ('duracaoAula', models.DurationField(help_text='Informe a duração da aula')),
                ('dataInicial', models.DateField(help_text='Informe a data de início da turma')),
                ('dataFinal', models.DateField(help_text='Informe a data de término da turma')),
                ('codigoTipoAtividade', models.CharField(help_text='Informe o código do tipo de atividade', max_length=70)),
                ('matriculaMonitor', models.CharField(help_text='Informe a matrícula do monitor', max_length=70, null=True)),
                ('idInsturor', models.CharField(help_text='Informe a matrícula do instrutor', max_length=70)),
            ],
        ),
    ]
