# Generated by Django 4.2.18 on 2026-06-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracaoAula',
            field=models.TimeField(help_text='Informe a duração da aula:'),
        ),
    ]
