# Generated by Django 4.2.18 on 2026-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_alter_turma_duracaoaula'),
        ('turma', '0003_turma_codigo_titulo_alter_turma_idinstrutor'),
    ]

    operations = [
    ]
