# Generated by Django 4.2.18 on 2026-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0004_merge_20260617_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracaoAula',
            field=models.TimeField(help_text='Informe a duração da aula', max_length=70),
        ),
    ]
