# Generated by Django 4.2.18 on 2026-06-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0005_alter_turma_duracaoaula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='idInstrutor',
            new_name='instrutor',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='matriculaMonitor',
            new_name='monitor',
        ),
    ]
